version: 2.1
orbs:
  # defined at https://github.com/snowdrop/circleci-orbs
  # needs to have been published before being used here
  openshift: snowdrop/openshift@0.4.0
jobs:
  openshift:
    machine: true

    steps:
      - checkout

      - openshift/launch_openshift

      # based on this: https://discuss.circleci.com/t/circle-2-0-caching-is-too-limited-to-be-very-useful/11694/10
      - restore_cache:
          keys:
            - secured-example-{{ .Branch }}-{{ checksum "pom.xml" }}
            - secured-example-{{ .Branch }}
            - secured-example

      - run:
          name: Install Maven dependencies locally
          command: |
            # Need to exclude tests since Maven will fail. See https://stackoverflow.com/q/14694139/2504224
            if ! ./mvnw -q -s .circleci/settings.xml dependency:go-offline; then
                parent_version=$(awk '/<parent>/{flag=1;next}/<\/parent>/{flag=0}flag' pom.xml | tail -1 | xargs | sed -e 's/<version>\(.*\)<\/version>/\1/')
                echo "Need to checkout the snowdrop-dependencies by checking it out from Github using version: ${parent_version}"

                pushd /tmp > /dev/null
                #Clone the snowdrop-dependencies from Github, checkout the tag that matches the BOM version and install it locally
                git clone https://github.com/snowdrop/spring-boot-bom.git
                cd spring-boot-bom
                git fetch --all --tags --prune
                git checkout tags/${parent_version}
                mvn install

                echo "Installed snowdrop-dependencies from source"

                popd > /dev/null
                #Re-execute command since the BOM has now been installed to the local .m2 directory
                ./mvnw -q -s .circleci/settings.xml dependency:go-offline
            fi

      - save_cache:
          paths:
            - ~/.m2
          key: secured-example-{{ .Branch }}-{{ checksum "pom.xml" }}

      - run:
          command: |
            oc new-project fmp
            .circleci/run_tests_with_fmp.sh -s .circleci/settings.xml
          no_output_timeout: 3600


workflows:
  version: 2
  build_and_test:
    jobs:
      - openshift
